# .github/workflows/deploy.yml

name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh fredp614@${{ secrets.SERVER_IP }} << 'EOF'
            # Navigate to app directory
            cd /home/fredp614/asphalt-app

            # Pull latest changes
            git pull origin main

            # Install dependencies if needed
            npm install --production

            # Restart the application
            sudo systemctl restart asphalt

            # Test Nginx config and reload if needed
            sudo nginx -t && sudo systemctl reload nginx

            # Clear any temporary files
            sudo rm -rf /tmp/mcguire-asphalt
          EOF
